author           = InnovAnon
depends          = default,ia_gutenberg,ia_util
description      = craft recipe graph analysis lib
name             = ia_crapht
optional_depends =
title            = IA Craft Recipe Graph Lib


